name: CI

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      # App
      APP_ENV: dev
      APP_LANG: fr
      APP_HOST: http://aikido-php
      # Database
      DB_USER: root
      DB_PASS: root
      DB_NAME: aikidorote1989
      DB_HOST: aikido-database
      # Credentials
      ADMIN_USER: "admin"
      ADMIN_PW: "@dm!n-pwd"
      # Mail
      MAIL_HOST: aikido-maildev
      MAIL_PORT: 1025
      MAILER: smtp

    steps:
      - uses: actions/checkout@v2

      - name: Build the docker-compose stack
        run: |
          docker-compose up -d
          sleep 10

      - name: Install dependencies
        run: composer install

      - name: Create .env
        run: docker exec aikido-php chmod +x scripts/setup_env.sh && ./scripts/setup_env.sh

      - name: Run migrations
        run: docker exec aikido-php php dump/migrations.php

      - name: Fill database
        run: docker exec aikido-php php dump/fill.php

      - name: Run tests
        run: docker exec aikido-php vendor/bin/phpunit
