name: CI

on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'master' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the docker-compose stack
        run: |
          docker-compose up -d
          sleep 10

      - name: Install dependencies
        run: composer install

      - name: Touch .env
        run: touch .env

      - name: Run migrations
        run: docker exec aikido-php php dump/migrations.php

      - name: Fill database
        run: docker exec aikido-php php dump/fill.php

      - name: Run tests
        run: docker exec aikido-php vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - run: mkdir ~/.ssh

      - run: touch hello_world

      - run: ssh-keyscan -H ${{ secrets.SFTP_HOST }} >> ~/.ssh/known_hosts

      - run: |
          username=${{ secrets.SFTP_USERNAME }}
          password=${{ secrets.SFTP_PASSWORD }}
          host=${{ secrets.SFTP_HOST }}

          RSYNC_PASSWORD=$password rsync hello_world $username@$host:/home/$username/test
