name: CI

on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'master' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v2

      - name: Generate .env file
        run: doppler run envsubst < .env.example > .env
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_DEV }}

      - name: Build the docker-compose stack
        run: |
          docker-compose up -d
          sleep 10

      - name: Install dependencies
        run: composer install

      - name: Run migrations
        run: docker exec aikido-php php dump/migrations.php

      - name: Fill database
        run: docker exec aikido-php php dump/fill.php

      - name: Run tests
        run: docker exec aikido-php vendor/bin/phpunit

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref_name == 'master'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node 🛠
        uses: actions/setup-node@v3

      - name: Semantic Release 🔥
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/release-notes-generator@10.0.3
            @semantic-release/git@10.0.1
            @semantic-release/github@8.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      - name: Generate .env file
        run: doppler run envsubst < .env.example > .env
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_PROD }}

      - name: Setup ssh
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H ${{ secrets.SFTP_HOST }} >> ~/.ssh/known_hosts

      - name: Install packages
        run: sudo apt install -y lftp git-restore-mtime

      - name: Restore git files modified time
        run: git restore-mtime

      - name: Install dependencies
        run: composer install --no-dev

      - name: Upload files
        run: |
          username=${{ secrets.SFTP_USERNAME }}
          password=${{ secrets.SFTP_PASSWORD }}
          host=${{ secrets.SFTP_HOST }}

          cmd_list="
            set sftp:auto-confirm yes;
            open $host;
            login $username $password;
            mirror --delete --reverse --verbose --only-newer . api \
              -x .* \
              -i app \
              -i public \
              -x public/assets/gallery \
              -x public/assets/images \
              -i utils \
              -i vendor \
              -I .env;
            quit;
          "

          lftp -e "$cmd_list"
